version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - go_app
    networks:
      - app-network
      - frontend-network

  nextjs:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nextjs_container
    networks:
      - frontend-network

  # go_app:
  #   build:
  #     context: ./go_app
  #     dockerfile: Dockerfile
  #   container_name: go_app_container
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - db
  #   networks:
  #     - app-network
  #   environment:
  #     - DB_HOST=db
  #     - DB_PORT=5432
  #     - DB_USER=postgres
  #     - DB_PASSWORD=postgres
  #     - DB_NAME=goapp

  db:
    image: postgres:13
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: goapp
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
  frontend-network:
    driver: bridge

volumes:
  db_data:
