name: Push to Remote Repository

on:
  push:
    branches:
      - main  # Trigger this workflow only on push to main branch

jobs:
  push_to_remote:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Push changes to remote
      run: |
        git remote add other_remote https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/2024-Hackathon-by-42-in-Asia/42-Tokyo-Repository.git
        git push other_remote konaito/readme-hello
